language: go

go:
 - master

install:
  # Install all external dependencies, ensuring they are updated.
  - go get -u -v $(go list -f '{{join .Imports "\n"}}{{"\n"}}{{join .TestImports "\n"}}' ./... | sort | uniq | grep -v golang-samples)
  # Install go-ipfs
  - curl https://ipfs.io/ipns/dist.ipfs.io/go-ipfs/v0.4.17/go-ipfs_v0.4.17_linux-amd64.tar.gz | tar xvz
  - export PATH=$PATH:$PWD/go-ipfs/
  - ipfs init
  # Install ffmeg
  - sudo add-apt-repository -y ppa:mc3man/trusty-media && sudo apt-get -qq update && sudo apt-get install -y ffmpeg

script:
 - ipfs daemon &
 - go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
